function u_seq = mpc_step_external( ...
    state_0, u_warm, u_last, u_delay, spline)

    params = evalin('base', 'params');

    refs = mpc_build_reference( ...
        state_0, spline, params);

    u_seq = mpc_solve_fmincon( ...
        state_0, ...
        u_warm, ...
        u_last, ...
        u_delay, ...
        refs, ...
        params);

end