function [H, f, Aineq, bineq, lb, ub] = ...
    lmpc_build_qp( ...
        xe0, Phi, Gamma, refs, ...
        u_prev_phys, params)

%% Cost
[H, f] = ...
    lmpc_build_cost( ...
        xe0, Phi, Gamma, params);


%% Magnitude constraints
[lb, ub] = ...
    lmpc_build_input_bounds( ...
        refs, params);


%% Input-rate constraints
[Aineq, bineq] = ...
    lmpc_build_rate_constraints( ...
        refs, u_prev_phys, params);

end